repos:
  # - repo: https://github.com/pre-commit/pre-commit-hooks
  #   rev: v2.3.0
  #   hooks:
  #     - id: check-yaml
  #     - id: end-of-file-fixer
  #     - id: trailing-whitespace
  - repo: local
    hooks:
      - id: unit-test
        name: unit-test
        entry: bash ./scripts/unit-test.sh
        language: system
        pass_filenames: false
